[versions]
kotlin-logging = "6.0.9"
boon = "0.34"
commons-lang3 = "3.17.0"
cyclonedx = "2.2.0"
gson = "2.10.1"
jackson = "2.18.3"
jacoco = "0.8.11"
jaxb-api = "2.3.1"
jersey = "2.42"
json-schema = "1.14.4"
json = "20190722"
juniversalchardet = "1.0.3"
kotlin = "1.9.25"
kotlinx-coroutines = "1.8.1"
kotter = "1.2.1"
picocli = "4.7.6"
slf4j = "2.0.17"
sonar-java = "6.8.0.23379"
sonarqube = "6.1.0.5360"
univocity-parsers = "2.9.1"
assertj = "3.26.3"
junit5 = "5.9.3"
junit-platform = "1.9.3"
ktlint = "12.1.2"
mockito-core = "3.12.4"
mockito-kotlin = "2.2.0"
mockk = "1.13.17"
wiremock = "2.35.2"

[libraries]
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
boon = { group = "io.fastjson", name = "boon", version.ref = "boon" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
univocity-parsers = { group = "com.univocity", name = "univocity-parsers", version.ref = "univocity-parsers" }
kotter = { group = "com.varabyte.kotter", name = "kotter-jvm", version.ref = "kotter" }
kotter-test = { group = "com.varabyte.kotterx", name = "kotter-test-support-jvm", version.ref = "kotter" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
jsonassert = { group = "org.skyscreamer", name = "jsonassert", version = "1.5.3" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
juniversalchardet = { group = "com.googlecode.juniversalchardet", name = "juniversalchardet", version.ref = "juniversalchardet" }
rxjava2 = { group = "io.reactivex.rxjava2", name = "rxjava", version = "2.2.21" }
jersey-client = { group = "org.glassfish.jersey.core", name = "jersey-client", version.ref = "jersey" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jackson-base = { group = "com.fasterxml.jackson", name = "jackson-base", version.ref = "jackson" }
jackson-dataformat-xml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jersey-hk2 = { group = "org.glassfish.jersey.inject", name = "jersey-hk2", version.ref = "jersey" }
javax-activation = { group = "com.sun.activation", name = "javax.activation", version = "1.2.0" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock", version.ref = "wiremock" }
json = { group = "org.json", name = "json", version.ref = "json" }
sonar-java-plugin = { group = "org.sonarsource.java", name = "sonar-java-plugin", version.ref = "sonar-java" }
jaxb-api = { group = "javax.xml.bind", name = "jaxb-api", version.ref = "jaxb-api" }
mockito-kotlin = { group = "com.nhaarman.mockitokotlin2", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
commons-text = { group = "org.apache.commons", name = "commons-text", version = "1.13.0" }
junit-platform-runner = { group = "org.junit.platform", name = "junit-platform-runner", version.ref = "junit-platform" }
json-schema = { group = "com.github.everit-org.json-schema", name = "org.everit.json.schema", version.ref = "json-schema" }

[plugins]
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
